update menu biodata mahasiswa, ambil data dari database new 2
katikunsri1960/SimakUnsri pull request #33
Opened 2024-01-18 09:06 UTC by ryanfitra

2024-01-18 14:56 UTC, chandraes requested changes

2024-01-18 14:56 UTC, chandraes commented on app/Models/Mahasiswa/RiwayatPendidikan.php
> +    public function getIdJalurMasukAttribute()
ini untuk ap?

2024-01-18 14:56 UTC, chandraes commented on resources/views/mahasiswa/biodata/include/akademik.blade.php
> +                                            value="{{$biodata->id_jalur_masuk}}">
jalur pendaftaran ini buat relasi dengan model jalur daftar

2024-01-18 14:56 UTC, chandraes commented on resources/views/mahasiswa/biodata/include/data-diri.blade.php
>                                      @if ($biodata->biodata->jenis_kelamin == "Laki-laki" )
ini kondisi untuk ap?

2024-01-19 04:10 UTC, ryanfitra commented on resources/views/mahasiswa/biodata/include/data-diri.blade.php
>                                      @if ($biodata->biodata->jenis_kelamin == "Laki-laki" )
untuk select otomatis di radio button sesuai nilai kak

2024-01-22 02:44 UTC, closed without merging